### ISSUE TITLE
replace hard exit in dftimewolf.config by BadConfig exception (or equiv)

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dftimewolf#157]
Some code clean up: https://github.com/log2timeline/dftimewolf/blob/master/dftimewolf/config.py#L79

Currently uses a hard exit without any explanation. I opt to replace it by a BadConfig exception (or equiv)

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dftimewolf/pull/196

**Comment by tomchop** [comment]
Fixed in https://github.com/log2timeline/dftimewolf/pull/196
