### ISSUE TITLE
Add user feedback that they are using an unsupported Python version

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dftimewolf#172]
Recent changes, require Python >=3.6 for dfTimewolf

Add user feedback that they are using an unsupported Python version to:
* setup.py,
* run_tests.py
* dftimewolf_recipes.py

e.g.

```
version_tuple = (sys.version_info[0], sys.version_info[1])
if version_tuple[0] != 3 or version_tuple < (3, 6):
  print((
      'Unsupported Python version: {0:s}, version 3.6 or higher '
      'required.').format(sys.version))
  sys.exit(1)
```

**Comment by tomchop** [comment]
This was done in https://github.com/log2timeline/dftimewolf/pull/174
