### ISSUE TITLE
Allow double registration of modules

### ISSUE THREAD

**Issue by tomchop** [log2timeline/dftimewolf#179]
Some wrappers around dftimewolf might want to replace an already registered module or recipe. Currently registering the same module / recipe twice with the new registry classes raises an exception. Should we change the codebase to unregister the module / recipe first, or should we pass a `force` or `overwrite` parameter to the method to ignore the exception?

**Comment by joachimmetz** [comment]
Let's chat about this. I'm not sure if I understand the use case to replace a recipe at runtime

**Comment by tomchop** [comment]
Fixed in https://github.com/log2timeline/dftimewolf/pull/199
