### ISSUE TITLE
Determine what needs to be done with incident_id in gcp_turbinia_import recipe

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dftimewolf#182]
incident_id in the gcp_turbinia_import recipe is set to now by default, though this is the only recipe that does this (other recipes that define incident_id don't)

Determine the desired behavior and make this uniform

Issue surfaced while working on https://github.com/log2timeline/dftimewolf/pull/169

**Comment by tomchop** [comment]
I assume you mean to `null`? Other recipes also use this notation when referring to `incident_id`. Maybe this was fixed along with the last changes.
