### ISSUE TITLE
KeyError with Timesketch upload

### ISSUE THREAD

**Issue by knsankar** [log2timeline/dftimewolf#270]
I am trying to run and upload grr artificate with _dftimewolf grr_artifact_ts_ . Once the plaso file got created, it is failed to upload to timesketch with following error.

Running external command: "log2timeline.py -q --status_view none --partition all --logfile /tmp/tmpr9c8zdrf/plaso.log /tmp/tmpr9c8zdrf/2d1c69396b2f48c3a23f275ba0fddd9a.plaso /tmp/tmpuu70uhlm/msedgewin10"
Module LocalPlasoProcessor completed
Uploading /tmp/tmpr9c8zdrf/2d1c69396b2f48c3a23f275ba0fddd9a.plaso to timeline msedgewin10
Module TimesketchExporter completed
dfTimewolf encountered one or more errors:
CRITICAL:   An unknown error occurred: 'objects'
Full traceback:
Traceback (most recent call last):
  File "/opt/dftimewolf/dftimewolf/lib/state.py", line 167, in _RunModuleThread
    module.Process()
  File "/opt/dftimewolf/dftimewolf/lib/exporters/timesketch.py", line 95, in Process
    self.timesketch_api.ExportArtifacts(named_timelines, self.sketch_id)
  File "/opt/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 141, in ExportArtifacts
    new_timeline_id = self._UploadTimeline(timeline_name, artifact_path)
  File "/opt/dftimewolf/dftimewolf/lib/timesketch_utils.py", line 124, in _UploadTimeline
    return response_dict['objects'][0]['id']
KeyError: 'objects'

Critical error found. Aborting.

**Comment by kiddinn** [comment]
the timesketch upload is not working ATM.

I'll fix it this week, has been on my agenda for a while now and I'm about to start that work. But unfortunately the timesketch upload functionality is broken
