### ISSUE TITLE
It's better to leave these arguments as positional args, so that they error out if the recipe is not providing everything it needs (a recipe developer will catch errors earlier on).

### ISSUE THREAD

**Issue by sa3eed3ed** [log2timeline/dftimewolf#338]
It's better to leave these arguments as positional args, so that they error out if the recipe is not providing everything it needs (a recipe developer will catch errors earlier on).

(in another PR) It might be good to change this across the whole codebase.

_Originally posted by @tomchop in https://github.com/log2timeline/dftimewolf/pull/317#discussion_r495842768_

**Comment by tomchop** [comment]
Tracking in https://github.com/log2timeline/dftimewolf/issues/415
