### ISSUE TITLE
Sort out error codes

### ISSUE THREAD

**Issue by tomchop** [log2timeline/dftimewolf#414]
Contributions like [metawolf](https://github.com/log2timeline/dftimewolf/pull/412/files#diff-a0e1184c64fee0ea6fb6daeffd4b5944803f2d6008e715fdc7066ae57c554427R201) are making heavy use of error codes. It would be nice to have different error codes:

* 0 - exit normally
* 1 - exit with error (noncritical)
* 2 - exit with critical error

**Comment by tomchop** [comment]
Or use this: https://tldp.org/LDP/abs/html/exitcodes.html

**Comment by giovannt0** [comment]
Any update on this? @tomchop
