### ISSUE TITLE
Collector / Recipe idea: gsheets_ts

### ISSUE THREAD

**Issue by jaegeral** [log2timeline/dftimewolf#465]
Based on: https://github.com/google/timesketch/issues/2024

- [ ] Create a collector for Google sheets that takes a doc id as parameter
- [ ] Collector stores data as pandas
- [ ] Check that the sheet cotains the required fields for timesketch
- [ ] create a recipe that triggers the collector and sends it to Timesketch
- [ ] add a optional parameter for worksheet ID. Default would be all worksheets

**Comment by itsmvd** [comment]
I would also recommend adding an optional parameter for a worksheet ID. Default would be all worksheets.

**Comment by tomchop** [comment]
"All worksheets" would mean one timeline per worksheet then?

**Comment by jaegeral** [comment]
I would imagine yes, every sheet would be a different timeline, as the columns would be (expected to be different) quite a lot.

However a ```--combine``` param to get it into one timeline should be easy to implement and then set all not existing key:value pairs to NaN.
