### ISSUE TITLE
`.format` vs f-strings

### ISSUE THREAD

**Issue by ramo-j** [log2timeline/dftimewolf#505]
As brought up my @itsmvd in pr/504 it might be worth shifting from `.format` style to f-strings. Raising this to establish whether this is a worthwhile change.

**Comment by tomchop** [comment]
Definitely is, given that we opened #391 a while back and still haven't adressed it. I think it makes sense migrating the whole codebase to f-strings.

**Comment by ramo-j** [comment]
Ahh I didn't look for an existing issue. Closing this in favour of the existing.
