### ISSUE TITLE
Move "attributes" attribute from from containers.containers.Report to containers.interface.AttributeContainer

### ISSUE THREAD

**Issue by jonathan-greig** [log2timeline/dftimewolf#507]
This will allow other container types to make use of generic attributes.

**Comment by jonathan-greig** [comment]
The "attributes" attribute was added to the `Report` container with https://github.com/log2timeline/dftimewolf/pull/158.

Appears that the only module currently using this "attributes" field is `TimeSketchEnhancer` [dftimewolf/lib/enhancers/timesketch.py#L476](https://github.com/log2timeline/dftimewolf/blame/main/dftimewolf/lib/enhancers/timesketch.py#L476):
```py
    report_attributes = [{'update_comment': True}]
    self.state.StoreContainer(containers.Report(
        module_name='TimesketchEnhancer', text_format=self._formatter.FORMAT,
        text='\n'.join(summary_lines), attributes=report_attributes))
```

This does not match the comment for this attribute [dftimewolf/lib/containers/containers.py#L56](https://github.com/log2timeline/dftimewolf/blob/main/dftimewolf/lib/containers/containers.py#L56) which expects a list of dicts with keys "name", "type" and "values":

```py
    attributes (list): attribute list, dicts must contain 'name',
      'type', 'values' keys.
```

**Comment by tomchop** [comment]
Indeed, this is not a great implementation. Let's remove this part for now, as the TimesketchEnhancer is set to be revisited anyways.
