### ISSUE TITLE
Github PR actiosn failing with `ModuleNotFoundError: No module named 'setuptools_rust'`

### ISSUE THREAD

**Issue by ramo-j** [log2timeline/dftimewolf#575]
Example: https://github.com/log2timeline/dftimewolf/runs/5748380736?check_suite_focus=true

**Comment by Digitalisx** [comment]
I forgot to link the issue with PR. 
So, it couldn't be closed automatically when merged.
If there is no other problem, I think the issue can be closed.
Thank you for raising the issue! 😊
