### ISSUE TITLE
Thread safety issue in Turbinia modules

### ISSUE THREAD

**Issue by ramo-j** [log2timeline/dftimewolf#600]
It appears that turbinia modules are subject to the same thread safety issue referenced [here](https://github.com/log2timeline/dftimewolf/blob/main/dftimewolf/lib/exporters/s3_to_gcs.py#L115) (among other places).

**Comment by sa3eed3ed** [comment]
Should this be fixed in Turbinia, instead of creating new clients?

**Comment by ramo-j** [comment]
My experience with other modules was that the issue lies in the http library in use by the GCP client. I'd assume that it's the same case with turbinia, and so the issue is further upstream.
